name = "ModPack nowyswiat"
author = "Nstyk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0637c98deee6502f49a86ccdbbb9caf367b45d96ad5562aa9e8211993c78379"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
