name = "ModPackPRO v1 Nowy Swiat"
author = "Nstyk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b300a461d49a373ce9a98dae98b8bfa694d4e0af8ee9917e0a9306a2cf6dc427"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
